# Generated by Django 3.2.16 on 2023-03-09 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230310_0029'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique subscription',
        ),
    ]
